import React from "react";
import styles from "./Disclaimer.module.css";

export default function Disclaimer({ onAccept }) {
  return (
    <div className={styles.container}>
      <div className={styles.card}>
        <div className={styles.header}>
          <div className={styles.icon}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={2}
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
              />
            </svg>
          </div>
          <h1 className={styles.title}>Important Notice & Disclaimer</h1>
          <p className={styles.subtitle}>Please review the information below to enter the site</p>
        </div>

        <div className={styles.divider}></div>

        <div className={styles.content}>
          <div className={styles.disclaimerItem}>
            <span className={styles.bullet}>•</span>
            <p className={styles.text}>
              This project is created <span className={styles.highlight}>strictly for educational and informational purposes only</span>.
            </p>
          </div>
          
          <div className={styles.disclaimerItem}>
            <span className={styles.bullet}>•</span>
            <p className={styles.text}>
              It should <span className={styles.highlight}>not be used for any real-world medical decisions</span>, including prediction of diseases or conditions, or self-diagnosis and usage of any herbal/ayurvedic medicines.
            </p>
          </div>

          <div className={styles.disclaimerItem}>
            <span className={styles.bullet}>•</span>
            <p className={styles.text}>
              The developer is <span className={styles.highlight}>not responsible for any misuse</span> of this system, its conversational AI health chatbot recommendations, or any other data generated by the application. Always consult a certified medical professional for real-world medical advice.
            </p>
          </div>
        </div>

        <div className={styles.divider}></div>

        <div className={styles.footer}>
          <button className={styles.btn} onClick={onAccept}>
            Accept & Enter Site
          </button>
        </div>
      </div>
    </div>
  );
}
